// const PAGE_NOT_FOUND = require('./PAGE_NOT_FOUND');
// const BAD_REQUEST = require('./BAD_REQUEST');
// const INTERNAL_SERVER_ERROR = require('./INTERNAL_SERVER_ERROR');

const PAGE_NOT_FOUND = 404;
const BAD_REQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;

module.exports = { PAGE_NOT_FOUND, BAD_REQUEST, INTERNAL_SERVER_ERROR };
